app:
    resource: @AppBundle/Controller/
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#HWIOAuthBundle routes
hwi_oauth_login:
   resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
   prefix:   /connect

hwi_oauth_redirect:
   resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
   prefix:   /connect

hwi_oauth_connect:
   resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
   prefix:   /connect
   
facebook_login:
    pattern: /login/check-facebook